spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:~/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    dbcp:
      default-auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
        proc:
          param_null_passing: true
  h2:
    console:
      path: /admin/h2-console
      enabled: true
      settings:
         trace: false
         web-allow-others: true
logging:
  level:
    ort.springframework.web: INFO
    org.springframework.ws.client.MessageTracing: INFO
    org.springframework.security: INFO
    org.springframework.data: INFO
    org.springframework.hibernate: DEBUG
    org.springframework.jdbc: TRACE
    org.h2: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE