INSERT INTO sources (id, description) VALUES (1, 'Printed');
INSERT INTO sources (id, description) VALUES (2, 'Softcopy');
INSERT INTO sources (id, description) VALUES (3, 'Cooking Light');
INSERT INTO sources (id, description) VALUES (4, 'Food & Wine');
INSERT INTO sources (id, description) VALUES (5, 'Eating Well');
INSERT INTO sources (id, description) VALUES (6, 'Sunset');
INSERT INTO sources (id, description) VALUES (7, 'Martha Stewart');
INSERT INTO sources (id, description) VALUES (8, 'Other');

INSERT INTO courses (id, description) VALUES (1, 'Appetizer');
INSERT INTO courses (id, description) VALUES (2, 'Bread');
INSERT INTO courses (id, description) VALUES (3, 'Soup/Stew');
INSERT INTO courses (id, description) VALUES (4, 'Salad');
INSERT INTO courses (id, description) VALUES (5, 'Entree');
INSERT INTO courses (id, description) VALUES (6, 'Seafood');
INSERT INTO courses (id, description) VALUES (7, 'Poultry');
INSERT INTO courses (id, description) VALUES (8, 'Meats');
INSERT INTO courses (id, description) VALUES (9, 'Beverage');
INSERT INTO courses (id, description) VALUES (10, 'Dessert');
INSERT INTO courses (id, description) VALUES (11, 'Dressing/Condiment');
INSERT INTO courses (id, description) VALUES (12, 'Vegetarian');
INSERT INTO courses (id, description) VALUES (13, 'Vegetable Side');
INSERT INTO courses (id, description) VALUES (14, 'Starch Side');
INSERT INTO courses (id, description) VALUES (15, 'Breakfast');

INSERT INTO ethnicities (id, description) VALUES (1, 'African');
INSERT INTO ethnicities (id, description) VALUES (2, 'Asian (other)');
INSERT INTO ethnicities (id, description) VALUES (3, 'Chinese');
INSERT INTO ethnicities (id, description) VALUES (4, 'Vietnamese');
INSERT INTO ethnicities (id, description) VALUES (5, 'Japanese');
INSERT INTO ethnicities (id, description) VALUES (6, 'Korean');
INSERT INTO ethnicities (id, description) VALUES (7, 'Thai');
INSERT INTO ethnicities (id, description) VALUES (8, 'Indian');
INSERT INTO ethnicities (id, description) VALUES (9, 'French');
INSERT INTO ethnicities (id, description) VALUES (10, 'Italian');
INSERT INTO ethnicities (id, description) VALUES (11, 'Mexican');
INSERT INTO ethnicities (id, description) VALUES (12, 'Southwest');
INSERT INTO ethnicities (id, description) VALUES (13, 'Middle Eastern');
INSERT INTO ethnicities (id, description) VALUES (14, 'Greek');
INSERT INTO ethnicities (id, description) VALUES (15, 'Spanish');
INSERT INTO ethnicities (id, description) VALUES (16, 'South American');
INSERT INTO ethnicities (id, description) VALUES (17, 'Southern');
INSERT INTO ethnicities (id, description) VALUES (18, 'Cajun/Creole');
INSERT INTO ethnicities (id, description) VALUES (19, 'Other');

INSERT INTO categories (id, description) VALUES (1, 'Fast');
INSERT INTO categories (id, description) VALUES (2, 'Healthy');
INSERT INTO categories (id, description) VALUES (3, 'Make Ahead');
INSERT INTO categories (id, description) VALUES (4, 'Easy');
INSERT INTO categories (id, description) VALUES (5, 'Slow Cooker');

INSERT INTO ratings (id, description) VALUES (1, 'No Rating');
INSERT INTO ratings (id, description, numeric_value) VALUES (2, '1', 1);
INSERT INTO ratings (id, description, numeric_value) VALUES (3, '2', 2);
INSERT INTO ratings (id, description, numeric_value) VALUES (4, '3', 3);
INSERT INTO ratings (id, description, numeric_value) VALUES (5, '4', 4);
INSERT INTO ratings (id, description, numeric_value) VALUES (6, '5', 5);